### ISSUE TITLE
请不要抄袭文档

### ISSUE THREAD

**Issue by illuspas** [AnyRTC/AnyRTC-RTMP#14]
请不要打着开源的旗子搞拿来主义，连文档都抄袭。  
抄就不说了，抄了还乱改。“集优化H.264软/硬件编码器”这句什么意思？本人原文里写的是“NEON指令集优化H.264软件编码器”，你们这句“集优化”是什么意思？“NEON指令集”是一个整词，不要贻笑大方，这么多人看着呢。

**Comment by DyncEric** [comment]
不好意思，文档这块没有注意，稍后将做修改。
感谢你提供的宝贵意见。

**Comment by dourgulf** [comment]
求楼主的项目:)

**Comment by begeekmyfriend** [comment]
@dourgulf 应该说的是这个——[NEON/SSE指令集优化H.264软件编码器](http://www.nodemedia.cn/client/NodeMediaClient-Android/)
