### ISSUE TITLE
请问下android端咋样使用啊

### ISSUE THREAD

**Issue by ab503044120** [AnyRTC/AnyRTC-RTMP#33]
我两台机子编译完成下载之后如何去操作推流和拉流

**Comment by DyncMing** [comment]
一个手机输入rtmp地址，点推流按钮， 另外一个手机输入相同的rtmp地址，点拉流按钮即可。

 

发件人: ab503044120 [mailto:notifications@github.com] 
发送时间: 2016年9月29日 17:58
收件人: AnyRTC/AnyRTC-RTMP
主题: [AnyRTC/AnyRTC-RTMP] 请问下android端咋样使用啊 (#33)

 

我两台机子编译完成下载之后如何去操作推流和拉流

**Comment by ab503044120** [comment]
谢谢您的回复,,我两台机器在一个局域网,同时输入rtmp://192.168.0.105但后一台点击推流一台点击拉流收不到,要输入什么样的rtmp地址呢,难道要需要中继的一个端吗

**Comment by DyncMing** [comment]
请问一下您搞的有rtmp的服务器么？

 

发件人: ab503044120 [mailto:notifications@github.com] 
发送时间: 2016年10月9日 9:11
收件人: AnyRTC/AnyRTC-RTMP
抄送: DyncMing; Comment
主题: Re: [AnyRTC/AnyRTC-RTMP] 请问下android端咋样使用啊 (#33)

 

谢谢您的回复,,我两台机器在一个局域网,同时输入rtmp://192.168.0.105但后一台点击推流一台点击拉流收不到,要输入什么样的rtmp地址呢,难道要需要中继的一个端吗

**Comment by ab503044120** [comment]
没有

**Comment by DyncMing** [comment]
那您首先先在本地搭建一个rtmp服务器， github上面有开源的srs， nginx-rtmp等。

 

发件人: ab503044120 [mailto:notifications@github.com] 
发送时间: 2016年10月9日 9:32
收件人: AnyRTC/AnyRTC-RTMP
抄送: DyncMing; Comment
主题: Re: [AnyRTC/AnyRTC-RTMP] 请问下android端咋样使用啊 (#33)

 

没有

**Comment by ab503044120** [comment]
没做好功课,谢谢指导,我去试试

**Comment by ab503044120** [comment]
推荐一个直接可以用的rtmp服务器 地址:https://github.com/illuspas/nginx-rtmp-win32 直接点击niginx.exe就可以用两端输入rtmp://192.168.0.105:1935/live/stream就可以用了(192.168.0.105为本机ip地址),大家有需要的参考下吧

**Comment by DyncEric** [comment]
谢谢共享
