### ISSUE TITLE
iOS 推流的时候 链接rtmp服务失败

### ISSUE THREAD

**Issue by linKnowEasy** [AnyRTC/AnyRTC-RTMP#36]
问下是不是有特殊的需求？？
rtmp 地址我用其他的直播 SDK 测试是 OK的

还是这个和其他的 直播SDK, 在对 rtmp URL 上有不同的要求
log如下

```
2016-10-13 17:07:16.502107 AnyRtmp[9381:1595552] OnRtmpStreamReconnecting:1
2016-10-13 17:07:16.508846 AnyRtmp[9381:1595552] OnRtmpStreamReconnecting:2
2016-10-13 17:07:16.514094 AnyRtmp[9381:1595552] OnRtmpStreamReconnecting:3
2016-10-13 17:07:16.517658 AnyRtmp[9381:1595552] OnRtmpStreamFailed:1
```

希望能够得到回复, 谢谢

**Comment by linKnowEasy** [comment]
重复几次就成功了。。。尴尬

**Comment by DyncEric** [comment]
请问下，使用的是什么服务器程序

**Comment by linKnowEasy** [comment]
用的 UPYUN 的一个测试地址，rtmp://testlivesdk.v0.upaiyun.com/live/test13
之后好像没有复现


然后就是刚刚测试的时,  退出直播时, 报错 
![test](http://i1.piimg.com/4851/e5196327c9c20164.jpg)

对C++ 不是很了解, 只能给出 截图了, 不好意思

**Comment by linjiansheng** [comment]
早上我也遇到了，重试几次就可以了又可以连上服务器，服务器是用srs部署在局域网的

**Comment by sodwell** [comment]
腾讯云centos，推不上去，用的SRS，用SRS自己的工具能推上去，本地局域网的用ubuntu可以，就是延时越来越大

**Comment by gstream** [comment]
hey @linKnowEasy , i am facing same issue with you. Did you resolve this issue ?

**Comment by linKnowEasy** [comment]
@gstream    after  retry several times, is work well. 
sorry , I don't know why.
