### ISSUE TITLE
How to set GOP parameters

### ISSUE THREAD

**Issue by jianwu** [AnyRTC/AnyRTC-RTMP#51]
I noticed in Android version (6, XIaomi Node), the RTMP stream has a GOP duration of 20 seconds, which cause long latency if enable GOP cache. Otherwise, there's long waiting time for the keyframe when starting play if we turn off GOP cache. 

I can't find an API to set KEY_FRAME_INTERVAL parameter anywhere. Please advice. 

Thanks

**Comment by DyncEric** [comment]
Yeah,  KEY_FRAME_INTERVAL  parameter need set in MediaFormat, for example:
MediaFormat format = MediaFormat.createVideoFormat(mime, width, height);
format.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, keyFrameIntervalSec);
mediaCodec.configure(format, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE);

**Comment by jianwu** [comment]
I didn't see any reference of "mdeiaCodec" in the AnyRTC-RTMP interface. How can I set this parameters based the API provided by AnyRTC-RTMP.

**Comment by DyncEric** [comment]
You can find it in MediaCodecVideoEncoder.java.

**Comment by jinghao666** [comment]
俩中国人非要用其他语言交流，are you zhuangbi？

**Comment by Whiplash777** [comment]
总有一些人自己不行还喷别人。好可悲。

**Comment by DyncEric** [comment]
这哥们用英文发问题，应该用英文回答吧？  @jinghao666    哪里有问题吗

**Comment by jianwu** [comment]
Thanks. I see it. Will try that. 

关于中英文，比较好奇@jinghao666会有这种奇葩想法。在国外呆久了，技术交流比较习惯用英文。而且在github上开源的项目面对全世界，我也是鼓励可能的话多用英文交流，这对开源项目的推广会有帮助。
