### ISSUE TITLE
srs_rtmp_is_onMetaData返回no flv

### ISSUE THREAD

**Issue by zhenghx1105** [AnyRTC/AnyRTC-RTMP#72]
我在用某app的rtmp做拉流测试的时候 碰到
else if (type == SRS_RTMP_TYPE_SCRIPT) {
		if (!srs_rtmp_is_onMetaData(type, data, size)) {
			LOG(LS_ERROR) << "No flv";
			srs_human_trace("drop message type=%#x, size=%dB", type, size);
		}
	}
srs_rtmp_is_onMetaData 返回否，请问如何解决 谢谢！

**Comment by DyncEric** [comment]
Meta信息只是视频流的描述信息，有的推流设置了，有的没有设置。不影响的

**Comment by zhenghx1105** [comment]
thanks
