### ISSUE TITLE
安卓奔跑不起来，不知道是哪里配置的有问题

### ISSUE THREAD

**Issue by maxdylan** [AnyRTC/AnyRTC-RTMP#80]
报这个错
AnyRTC-RTMP\webrtc\base\atomicops.h
Error:(63, 31) error: '__ATOMIC_ACQUIRE' was not declared in this scope
Error:(63, 47) error: '__atomic_load_n' was not declared in this scope
Error:(66, 32) error: '__ATOMIC_RELEASE' was not declared in this scope
Error:(66, 48) error: '__atomic_store_n' was not declared in this scope
Error:(74, 33) error: '__ATOMIC_ACQUIRE' was not declared in this scope

**Comment by DyncMing** [comment]
Ndk 用的哪个版本？

 

发件人: WhichHuo [mailto:notifications@github.com] 
发送时间: 2017年5月19日 13:04
收件人: AnyRTC/AnyRTC-RTMP
抄送: Subscribed
主题: [AnyRTC/AnyRTC-RTMP] 安卓奔跑不起来，不知道是哪里配置的有问题 (#80)

 

报这个错
AnyRTC-RTMP\webrtc\base\atomicops.h
Error:(63, 31) error: '__ATOMIC_ACQUIRE' was not declared in this scope
Error:(63, 47) error: '__atomic_load_n' was not declared in this scope
Error:(66, 32) error: '__ATOMIC_RELEASE' was not declared in this scope
Error:(66, 48) error: '__atomic_store_n' was not declared in this scope
Error:(74, 33) error: '__ATOMIC_ACQUIRE' was not declared in this scope

**Comment by maxdylan** [comment]
更新了下ndk，确实好了，多谢，还有个问题，我用两个手机，局域网内，一个手机给另一个手机推流，可以直接推过去，不经过服务器么？或者在某一部手机上实现服务器的功能？

**Comment by DyncMing** [comment]
那你可以考虑p 2 p ，直播肯定得有服务器的。
------------------ Original ------------------

**Comment by maxdylan** [comment]
也不是做直播啦，就是实现这种一对一的，并且还是在局域网下的这种形式，你觉得在安卓端搭建一个这种服务器可操作性怎么样？因为我对服务器这些不是很了解，连接设备不会很多，也就两三台的样子，我也就是自己瞎搞，如果涉及到什么不能说的，我先说声对不起哈  ^_^

**Comment by DyncEric** [comment]
问题解决了吗，解决了的话，关闭这个issue吧
